provider-list:
  providers:
    -
      name: provider1
      url: https://provider1.com/v1/api/account/validate

    -
      name: provider2
      url: https://provider2.com/v2/api/account/validate

spring:
  profiles:
    active: test

server:
  error:
    include-message: always
    include-binding-errors: always